name: Playwright Tests

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: "01,43 * * * *"  # Runs at :01 and :43 every hour (UTC)

jobs:
  test:
    timeout-minutes: 10
    runs-on: ubuntu-22.04

    steps:
      - name: Debug Current Time (UTC)
        run: date

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Cache Playwright Browsers
        uses: actions/cache@v4
        with:
          path: ~/.cache/ms-playwright
          key: ${{ runner.os }}-playwright-${{ hashFiles('**/package-lock.json') }}

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install Dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps chromium

      - name: Create .env File
        run: |
          touch .env
          echo "EMAIL=${{ secrets.EMAIL }}" >> .env
          echo "PASSWORD=${{ secrets.PASSWORD }}" >> .env
          echo "MAX_FUEL_PRICE=${{ vars.MAX_FUEL_PRICE }}" >> .env
          echo "MAX_CO2_PRICE=${{ vars.MAX_CO2_PRICE }}" >> .env

      - name: Run Playwright Tests
        run: npx playwright test

      # Uncomment this to upload the HTML test report as an artifact
      # - name: Upload Playwright Report
      #   uses: actions/upload-artifact@v4
      #   if: always()
      #   with:
      #     name: playwright-report
      #     path: playwright-report/
      #     retention-days: 1
